/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Prominic_jdi_system_Win32PKDll */

#ifndef _Included_com_Prominic_jdi_system_Win32PKDll
#define _Included_com_Prominic_jdi_system_Win32PKDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    applications
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_Prominic_jdi_system_Win32PKDll_applications
  (JNIEnv *, jobject);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    processes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_Prominic_jdi_system_Win32PKDll_processes
  (JNIEnv *, jobject);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    app2pid
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_Prominic_jdi_system_Win32PKDll_app2pid
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    pid2exename
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_Prominic_jdi_system_Win32PKDll_pid2exename
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    exist_pid
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Prominic_jdi_system_Win32PKDll_exist_1pid
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    kill
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Prominic_jdi_system_Win32PKDll_kill
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    kill_tree
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_Prominic_jdi_system_Win32PKDll_kill_1tree
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    get_tree
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_Prominic_jdi_system_Win32PKDll_get_1tree
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    startService
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Prominic_jdi_system_Win32PKDll_startService
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    stopService
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Prominic_jdi_system_Win32PKDll_stopService
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    isRunningService
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Prominic_jdi_system_Win32PKDll_isRunningService
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    isConfiguredService
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Prominic_jdi_system_Win32PKDll_isConfiguredService
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    listServices
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_Prominic_jdi_system_Win32PKDll_listServices
  (JNIEnv *, jobject);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    service2pid
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_Prominic_jdi_system_Win32PKDll_service2pid
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    getServiceState
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_Prominic_jdi_system_Win32PKDll_getServiceState
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    getServiceControls
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_Prominic_jdi_system_Win32PKDll_getServiceControls
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    isServiceDBLocked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_Prominic_jdi_system_Win32PKDll_isServiceDBLocked
  (JNIEnv *, jobject);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    serviceName2DisplayName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_Prominic_jdi_system_Win32PKDll_serviceName2DisplayName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    displayName2ServiceName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_Prominic_jdi_system_Win32PKDll_displayName2ServiceName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    isDebugPrivilegeEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_Prominic_jdi_system_Win32PKDll_isDebugPrivilegeEnabled
  (JNIEnv *, jobject);

/*
 * Class:     com_Prominic_jdi_system_Win32PKDll
 * Method:    enableDebugPrivilege
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_Prominic_jdi_system_Win32PKDll_enableDebugPrivilege
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
